channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=23.2.1
- pip:
  - mlflow==2.5.0
  - numpy==1.25.1
  - packaging==23.1
  - pandas==2.0.3
  - pillow==10.0.0
  - protobuf==3.19.6
  - requests==2.31.0
  - scipy==1.11.1
  - tensorflow-gpu==2.10.0
  - tensorflow==2.10.0
name: mlflow-env
